### PR TITLE
Add typescript definitions

### LINKED ISSUE #7: Typescript definitions
I use typescript when possible and I have written some basic definitions for this SDK. I would like to contribute them to this repository if possible. Feedback on the idea and then the definitions themselves would be awesome!

### PR DESCRIPTION
**Pull request by mnalsup**
The user-facing components are documented here. There is room for improvement in carrying over documentation and possibly filling out "any" types. But I have been able to use these successfully for the US Street API.

closes #7

### CODE REVIEW

**Comment by cbuchert** [comment]
@mnalsup we've been talking internally about this pull request. The big concern is that it's effectively double documentation for the repository and it would be easy for it to go out of sync with the rest of the code base. Given that, we're going to hold off on merging this in.

That being said, moving to TypeScript is being considered at this point so this file could be moot anyway. Thanks for contributing and working with us.

**Comment by toby5box** [comment]
Perhaps these could be contributed to DefinitelyTyped. https://devblogs.microsoft.com/typescript/writing-dts-files-for-types/

**Comment by camiblanch** [comment]
@toby5box I don't know a lot about DefinitelyTyped. Would that require us to maintain documentation somewhere else as well? We would really like to keep it to a max of 1 location for documentation.

**Comment by TangrisJones** [comment]
@cbuchert Has there been any progress towards moving to typescript? Thanks!

**Comment by camiblanch** [comment]
@TangrisJones There has not been any progress on moving this to typescript besides what you see in this thread.

**Comment by chadly** [comment]
Y'all should've just merged this PR. The types are being maintained now separately in DefinitelyTyped. Oh well....

For anyone else that stumbles upon this, just run:

```
npm i @types/smartystreets-javascript-sdk
```

to get type definitions.

**Pull request closed without merging**
